image: alpine:latest

.auto-deploy:
  image: "git.ia.surfsara.nl:5050/automation/build-container/master"

variables:
  POSTGRES_ENABLED: "false"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  ROLLOUT_RESOURCE_TYPE: "deployment"

stages:
  - build
  - test
  - review
  - development
  - staging
  - production
  - performance
  - cleanup


include:
  - template: Jobs/Build.gitlab-ci.yml
  - template: Jobs/Code-Quality.gitlab-ci.yml
  - template: Jobs/Browser-Performance-Testing.gitlab-ci.yml

.test_script: &test_script |-
  mkdir -p -m 700 ~/.ssh
  ssh-keyscan git.ia.surfsara.nl >> ~/.ssh/known_hosts
  echo "$SSH_PRIVATE_KEY_BASE64_ENCODED" | base64 -d > ~/.ssh/id_rsa
  chmod 600 ~/.ssh/id_rsa
  pip install flake8 flake8-junit-report --quiet
  pip install -r requirements.txt --quiet

unit test:
  image: python:3.7
  stage: test
  script:
    - *test_script
    - flake8 jira_api --output-file flake8.txt && flake8_junit flake8.txt report-flake8.xml
  artifacts:
    reports:
      junit: report-*.xml


.deploy_script: &deploy_script
  script:
    - auto-deploy ensure_namespace
    - auto-deploy initialize_helm
    - auto-deploy prepare_chart
    - auto-deploy create_secret
    - auto-deploy deploy
    - auto-deploy persist_environment_url

deploy review:
  variables:
    KUBE_INGRESS_BASE_DOMAIN: review.automation.surf.net
  extends: .auto-deploy
  stage: review
  <<: *deploy_script
  only:
    refs:
      - branches
    kubernetes: active
  artifacts:
    paths: [environment_url.txt]
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: https://$CI_COMMIT_REF_SLUG-$CI_PROJECT_NAME.$KUBE_INGRESS_BASE_DOMAIN/jira/ui
    on_stop: stop_review
  except:
    refs:
      - dev
      - master
      - tags
      - schedules

deploy review base:
  variables:
    KUBE_INGRESS_BASE_DOMAIN: api.review.automation.surf.net
  extends: .auto-deploy
  stage: development
  <<: *deploy_script
  only:
    refs:
      - dev
    kubernetes: active
  artifacts:
    paths: [environment_url.txt]
  environment:
    name: review
    url: https://$KUBE_INGRESS_BASE_DOMAIN/jira/ui/
  except:
    refs:
      - master
      - tags
      - schedules

deploy dev:
  variables:
    KUBE_INGRESS_BASE_DOMAIN: api.dev.automation.surf.net
    DEPLOY_NAMESPACE: development
  extends: .auto-deploy
  stage: development
  <<: *deploy_script
  only:
    refs:
      - dev
    kubernetes: active
  artifacts:
    paths: [environment_url.txt]
  environment:
    name: development
    url: https://$KUBE_INGRESS_BASE_DOMAIN/jira/ui/
  except:
    refs:
      - master
      - tags
      - schedules

deploy staging:
  variables:
    KUBE_INGRESS_BASE_DOMAIN: api.staging.automation.surf.net
    DEPLOY_NAMESPACE: staging
  extends: .auto-deploy
  stage: staging
  <<: *deploy_script
  only:
    refs:
      - master
    kubernetes: active
  artifacts:
    paths: [environment_url.txt]
  environment:
    name: staging
    url: https://$KUBE_INGRESS_BASE_DOMAIN/jira/ui
  except:
    refs:
      - dev
      - tags
      - schedules

deploy production:
  variables:
    KUBE_INGRESS_BASE_DOMAIN: api.automation.surf.net
    DEPLOY_NAMESPACE: production
  extends: .auto-deploy
  stage: production
  <<: *deploy_script
  only:
    refs:
      - tags
    kubernetes: active
  artifacts:
    paths: [environment_url.txt]
  environment:
    name: production
    url: https://$KUBE_INGRESS_BASE_DOMAIN/jira/ui
  except:
    refs:
      - dev
      - master
      - schedules

stop_review:
  extends: .auto-deploy
  stage: cleanup
  variables:
    GIT_STRATEGY: none
  script:
    - auto-deploy initialize_helm
    - auto-deploy delete
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    action: stop
  when: manual
  allow_failure: true
  only:
    refs:
      - branches
    kubernetes: active
  except:
    refs:
      - dev
      - master
      - tags
