---
stages:
  - build
  - release
  - deploy

variables:
  CONTAINER_TEST_IMAGE: registry.automation.surf.net/nwa/workflows-client:$CI_COMMIT_SHA
  CONTAINER_STAGING_IMAGE: registry.automation.surf.net/nwa/workflows-client:staging
  CONTAINER_RELEASE_IMAGE: registry.automation.surf.net/nwa/workflows-client:latest

build docker image:
  stage: build
  image: docker:latest
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
  tags:
    - docker-ct-builder-ext

release image staging:
  stage: release
  image: docker:latest
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_STAGING_IMAGE
    - docker push $CONTAINER_STAGING_IMAGE
  tags:
    - docker-ct-builder-ext
  only:
    - staging@SURFnetNOC/workflows-client

release image prod:
  stage: release
  image: docker:latest
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  tags:
    - docker-ct-builder-ext
  only:
    - master@SURFnetNOC/workflows-client

deploy to staging:
  stage: deploy
  script:
    - ssh deploy@swarm01.staging.automation.surf.net  "sudo docker service update --image $CONTAINER_STAGING_IMAGE staging_workflows-client"
  environment:
    name: staging
    url: https://workflows.staging.automation.surf.net/
  tags:
    - shell-ext
  only:
    - staging@SURFnetNOC/workflows-client

deploy to prod:
 stage: deploy
 script:
   - ssh deploy@swarm01.automation.surf.net  "sudo docker service update --image $CONTAINER_RELEASE_IMAGE prod_workflows-client"
 environment:
   name: prod
   url: https://workflows.automation.surf.net/
 tags:
   - shell-ext
 only:
   - master@SURFnetNOC/workflows-client
