env:
    REACT_APP_BACKEND_URL: "https://orchestrator.dev.automation.surf.net"
    REACT_APP_OAUTH2_ENABLED: "false"
    REACT_APP_OAUTH2_OPENID_CONNECT_URL: ""
    REACT_APP_OAUTH2_CLIENT_ID: ""
    REACT_APP_OAUTH2_SCOPE: "openid"
    REACT_APP_CHECK_STATUS_INTERVAL: "3"
    REACT_APP_NETWORKDASHBOARD_URL: https://netwerkdashboard.review.automation.surf.net
