# Default values for orchestrator-client.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: git.ia.surfsara.nl:5050/automation/orchestrator-client/dev
  tag: stable
  pullPolicy: IfNotPresent
  secrets: "gitlab-registry"

configMapName: "orchestrator-client-configuration"

nameOverride: "orchestrator-client"
fullnameOverride: "orchestrator-client_service"

service:
  name: orchestrator-client
  type: ClusterIP
  port: 80
  internalPort: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  paths:
    - /(.*)
  defaultHost: orchestrator.review.automation.surf.net
  environmentUrl:
  tls:
    secretName: tls-secret

resources:
   limits:
     memory: 128Mi
   requests:
     memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

livenessProbe:
  path: /api/user/config
  failureThreshold: 3
  periodSeconds: 30
  timeoutSeconds: 10

readinessProbe:
  path: /api/user/config
  failureThreshold: 3
  periodSeconds: 30
  timeoutSeconds: 10

env:

secret:
  secretChecksum:
  secretName:
