apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.env }}
data:
    {{- toYaml . | nindent 8 }}
{{- end }}
